site_name: "ЛР — Filatov Arseny (k3339)"
site_description: Отчётные материалы по дисциплине Web-программирование
docs_dir: docs
site_dir: site
theme:
  name: mkdocs
  language: ru
nav:
  - Главная: index.md
  - Лабораторная работа 1:
      - Обзор: lr1.md
      - "Практика 1.1 — in-memory": practice_1_1.md
      - "Практика 1.2 — PostgreSQL": practice_1_2.md
      - "Практика 1.3 — Alembic и JWT": practice_1_3.md
